# Generated by Django 4.0.1 on 2022-07-12 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
